type correction for array color, that fix the issue : Traffic-Simulator\src\Vehicle.cpp(101,38): error C2440: 'initializing': cannot convert from 'std::array<float,3>' to 'const std::array<double,3>'